import { defineType, defineField } from 'sanity'

export const siteSettings = defineType({
  name: 'siteSettings',
  title: 'Site Settings (Global)',
  type: 'document',
  description: 'Appears EVERYWHERE on the website. Only 1 document needed. REPLACE values to update contact info, social links, and SEO.',
  groups: [
    { name: 'contact', title: 'Contact Info' },
    { name: 'social', title: 'Social Links' },
    { name: 'seo', title: 'SEO / Meta' },
  ],
  fields: [
    defineField({
      name: 'siteName',
      title: 'Site Name',
      type: 'string',
      group: 'seo',
      description: 'REPLACE: Your business name (e.g. "Hola Beauty Parlour"). Shows in browser tab and search results.',
      initialValue: 'Hola Beauty Parlour',
    }),
    defineField({
      name: 'phone',
      title: 'Phone Number',
      type: 'string',
      group: 'contact',
      description: 'REPLACE: Your primary phone/WhatsApp number. Shows in Navbar, Footer, Contact page, and Floating WhatsApp button.',
      initialValue: '+91 94909 39727',
    }),
    defineField({
      name: 'email',
      title: 'Email Address',
      type: 'string',
      group: 'contact',
      description: 'REPLACE: Your business email. Shows on Contact page and Footer.',
      initialValue: 'holanellore@gmail.com',
    }),
    defineField({
      name: 'address',
      title: 'Full Address',
      type: 'text',
      rows: 3,
      group: 'contact',
      description: 'REPLACE: Your complete address. Shows on Contact page and Footer.',
      initialValue: 'Near Mahila Pranganam Gate, Santhinagar, Nellore',
    }),
    defineField({
      name: 'mapEmbedUrl',
      title: 'Google Maps Embed URL',
      type: 'url',
      group: 'contact',
      description: 'REPLACE: Paste the full Google Maps embed URL (src="...") to update the map on Homepage and Contact page.',
    }),
    defineField({
      name: 'whatsappLink',
      title: 'WhatsApp Link',
      type: 'url',
      group: 'social',
      description: 'REPLACE: Your WhatsApp URL (e.g. https://wa.me/919490939727). Used in Floating button and Contact page.',
    }),
    defineField({
      name: 'instagramLink',
      title: 'Instagram Link',
      type: 'url',
      group: 'social',
      description: 'REPLACE: Your Instagram profile URL. Used in Contact page and social links.',
    }),
    defineField({
      name: 'workingHours',
      title: 'Working Hours',
      type: 'text',
      rows: 5,
      group: 'contact',
      description: 'REPLACE: Update your business hours. Shows on Contact page.',
      initialValue: 'Mon - Fri: 9:00 AM - 8:00 PM\nSat: 8:00 AM - 9:00 PM\nSun: 9:00 AM - 6:00 PM\nHolidays: By Appointment',
    }),
    defineField({
      name: 'seoDescription',
      title: 'SEO Description (Meta)',
      type: 'text',
      rows: 2,
      group: 'seo',
      description: 'REPLACE: Short description shown in Google search results (max ~160 chars).',
    }),
    defineField({
      name: 'seoKeywords',
      title: 'SEO Keywords',
      type: 'text',
      rows: 2,
      group: 'seo',
      description: 'REPLACE: Comma-separated keywords for search engines (e.g. beauty parlour, makeup artist, bridal makeup).',
    }),
  ],
  preview: {
    select: { title: 'siteName' },
  },
})
